# pins-values are based on raspi pin-numbering.

lights:
    building:
        off: false
        on: true
        pin: 7
        provider: ''
    twitter:
        off: false
        on: true
        pin: 7
        provider: ''
        consumerKey: ''
        consumerSecret: ''
        accessTokenKey: ''
        accessTokenSecret: ''
        statusTrack: ''
    pass:
        off: false
        on: true
        pin: 7
        provider: ''
    fail:
        off: false
        on: true
        pin: 7
        provider: ''
        exclusionList: []
teamcity:
    user: ''
    password: ''
    queryInterval: ''
    baseUri: ''
    buildStatusQueryInterval: ''
port: 8080